CREATE DATABASE WEI;
USE Wei;

CREATE TABLE COUNTRY
(
  Id INT auto_increment,
  Name VARCHAR(15) not null, 
  Rods VARCHAR (40),
  PRIMARY KEY (Id)
);

CREATE TABLE WEI2022
(
  Id INT NOT NULL auto_increment,
  Percenty DOUBLE NOT NULL, 
  PRIMARY KEY (Id)
);

CREATE TABLE WEG2022
(
  Id INT NOT NULL auto_increment,
  Name VARCHAR(15) NOT NULL, 
  PRIMARY KEY (Id)
);

CREATE TABLE GGPI2022
(
  Id INT NOT NULL auto_increment,
  Percenty DOUBLE NOT NULL, 
  PRIMARY KEY (Id)
);


CREATE TABLE GPG2022
(
  Id INT NOT NULL auto_increment,
  Name VARCHAR(15) NOT NULL, 
  PRIMARY KEY (Id)
);

CREATE TABLE HDG2021
(
  Id INT NOT NULL auto_increment,
  Name VARCHAR(20) NOT NULL, 
  PRIMARY KEY (Id)
);

CREATE TABLE  Indications (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Id_COUNTRY INT,
  Id_WEI2022 INT,
  Id_WEG2022 INT,
  Id_GGPI2022 INT,
  Id_GPG2022 INT,
  Id_HDG2021 INT,
 
  
  CONSTRAINT fk_COUNTRY FOREIGN KEY (Id_COUNTRY) REFERENCES COUNTRY (Id),
  CONSTRAINT fk_WEI2022 FOREIGN KEY (Id_WEI2022) REFERENCES WEI2022 (Id),
  CONSTRAINT fk_WEG2022 FOREIGN KEY (Id_WEG2022) REFERENCES WEG2022 (Id),
  CONSTRAINT fk_GGPI2022 FOREIGN KEY (Id_GGPI2022) REFERENCES GGPI2022 (Id),
  CONSTRAINT fk_GPG2022 FOREIGN KEY (Id_GPG2022) REFERENCES GPG2022 (Id),
  CONSTRAINT fk_HDG2021 FOREIGN KEY (Id_HDG2021) REFERENCES HDG2021 (Id)
);

