
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Iceland', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Norway', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Sweden', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Austria', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Bulgaria', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Canada', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Croatia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Czechia', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Estonia', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Finland', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('France', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Germany', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Hungary', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Ireland', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Italy', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Latvia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Lithuania', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Luxembourg', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Netherlands', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Poland', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Portugal', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Serbia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Singapore', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Slovenia', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Spain', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Switzerland', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('United Kingdom', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('United States', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Albania', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Armenia', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Bolivia (Plurinational State of)', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Brazil', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Chile', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('China', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Costa Rica', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Cyprus', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Dominican Republic', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Ecuador', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Greece', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Israel', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Jamaica', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Japan', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Malta', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Mauritius', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Moldova (Republic of)', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Mongolia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Montenegro', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Namibia', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('North Macedonia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Peru', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('DPhilippines', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Romania', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Slovakia', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('South Africa', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Thailand', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('United Arab Emirates', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Uruguay', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Viet Nam', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Bangladesh', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Belize', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Benin', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Bhutan', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Bosnia and Herzegovina', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Botswana', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Burkina Faso', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Burundi', 'Europe and Northern America');

INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Denmark', 'Europe and Northern America');
INSERT INTO PAIS (Name, Rods) VALUES ('Australia', 'Australia and New Zealand');
INSERT INTO PAIS (Name, Rods) VALUES ('Belgium', 'Europe and Northern America');