services:
  python:
    image: python
    entrypoint: tail -f /dev/null
    volumes:
      - .:/app
    working_dir: /app
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mysql_laguir
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '127.0.0.1:3307:3306'
    volumes:
      - .:/app
      - mysql-data:/var/lib/mysql

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: always
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admim
    volumes:
      - cassandra-data:/var/lib/cassandra
      - .:/app
    
volumes:
  cassandra-data:
  mysql-data:

