CREATE DATABASE WEI;
USE WEI;

CREATE TABLE  WEI_TABLE
(
  ID INT AUTO_INCREMENT,
  COUNTRY VARCHAR(50) NOT NULL,
  WEI_2022 DOUBLE NOT NULL,
  WEG_2022 VARCHAR(50) NOT NULL,
  GGPI_2022 DOUBLE NOT NULL,
  GPG_2022 VARCHAR(50) NOT NULL,
  HDG_2021 VARCHAR(50) NOT NULL,
  SDGR VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SDGR (
  ID INT AUTO_INCREMENT NOT NULL,
  REGION_NAME VARCHAR(100) NOT NULL, 
  PRIMARY KEY (ID)
);

CREATE TABLE COUNTRY (
  ID INT AUTO_INCREMENT,
  COUNTRY_NAME VARCHAR(50) NOT NULL,
  REGION_FK INT NOT NULL, 
  PRIMARY KEY (ID),

  FOREIGN KEY (REGION_FK) REFERENCES SDGR (ID)
);


CREATE TABLE WEI_2022 (
  ID INT AUTO_INCREMENT NOT NULL,
  INDEX_VALUE DOUBLE NOT NULL, 
  PRIMARY KEY (ID)
);

CREATE TABLE WEG_2022 (
  ID INT AUTO_INCREMENT NOT NULL,
  GROUP_NAME VARCHAR(50) NOT NULL, 
  PRIMARY KEY (ID)
);

CREATE TABLE GGPI_2022 (
  ID INT AUTO_INCREMENT NOT NULL,
  INDEX_VALUE DOUBLE NOT NULL, 
  PRIMARY KEY (ID)
);


CREATE TABLE GPG_2022 (
  ID INT AUTO_INCREMENT NOT NULL,
  GROUP_CLASSIFICATION VARCHAR(50) NOT NULL, 
  PRIMARY KEY (ID)
);

CREATE TABLE HDG_2021 (
  ID INT AUTO_INCREMENT NOT NULL,
  GROUP_CLASSIFICATION VARCHAR(50) NOT NULL, 
  PRIMARY KEY (ID)
);

CREATE TABLE  INDICATIONS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  COUNTRY_ID INT,
  WEI_2022_ID INT,
  WEG_2022_ID INT,
  GGPI_2022_ID INT,
  GPG_2022_ID INT,
  HDG_2021_ID INT,
  SDGR_ID INT,
  
  FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID),
  FOREIGN KEY (WEI_2022_ID) REFERENCES WEI_2022 (ID),
  FOREIGN KEY (WEG_2022_ID) REFERENCES WEG_2022 (ID),
  FOREIGN KEY (GGPI_2022_ID) REFERENCES GGPI_2022 (ID),
  FOREIGN KEY (GPG_2022_ID) REFERENCES GPG_2022 (ID),
  FOREIGN KEY (SDGR_ID) REFERENCES SDGR (ID)
);