version: '3.1'
services:
db: mysql_laguir
image: mysql
container_image: mysql_laguir
environment: 
MYSQL_DATABASE: mysql_laguir
MYSQL_ROOT_PASSWORD: root

ports:
 - 3306:3306
volumes:
- ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro


